Models/Competencia.cs
namespace WebAppBloom.Models;
public class Competencia{    
    public int Id { get; set; }
    
    public string? ColunaBloom { get; set; }

    public string? LinhaBloom { get; set; }

    public Competencia(){
        
    }

    public Competencia(string? colunaBloom, string? linhaBloom)
    {        
        ColunaBloom = colunaBloom;
        LinhaBloom = linhaBloom;
    }
}

ViewModels/CriarCompetenciaViewModel.cs
namespace WebAppBloom.ViewModels;
public class CriarCompetenciaViewModel{    
       
    public string? ColunaBloom { get; set; }

    public string? LinhaBloom { get; set; }
}

ViewModels/ListaCompetenciaViewModel.cs
using WebAppBloom.Models;
public class ListaCompetenciaViewModel
{
    /* Listar */
    public ICollection<Competencia> Competencias {get;set;} = new List<Competencia>();
    
}

Controllers/CompetenciaController.cs
using Microsoft.AspNetCore.Mvc;
using WebAppBloom.Models;
using WebAppBloom.ViewModels;
using WebAppBloom.Contexts;
namespace WebAppBloom.Controllers;
public class CompetenciaController:Controller{
    
    private readonly AppDbContext _context;

   public CompetenciaController(AppDbContext context){
        _context = context;
   } 
   public IActionResult Index(){

         var listaCompe = _context.Competencias.ToList();
            var listaViewModel = new ListaCompetenciaViewModel{

                  Competencias = listaCompe
            };
         return View(listaViewModel);
   }

   public IActionResult RelatorioCompe(){
      
      /*var competencia = new Competencia(){
           ColunaBloom = "Teste Coluna",
           LinhaBloom = "Teste Linha"
      };
      
      var viewModel = new DetalhesCompViewModel(){
            Competencia = competencia,
            TituloPagina = "Página de Teste"
      };*/
      var competencias = _context.Competencias.ToList();
      return View();




   }
      public IActionResult Listar(){
            var listaCompe = _context.Competencias.ToList();
            var listaViewModel = new ListaCompetenciaViewModel{

                  Competencias = listaCompe
            };
            return View(listaViewModel);
      }

       [HttpPost]
       public IActionResult Index(CriarCompetenciaViewModel dados){
            var competencia = new Competencia(dados.ColunaBloom, dados.LinhaBloom);
            _context.Add(competencia);
            _context.SaveChanges();
            return  RedirectToAction(nameof(Index));
       }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebAppBloom.Controllers
{
    public class HomeController : Controller
    {

        public IActionResult Index(){
            return View();
        }

    }
}

Views/Competencia/Index.cshtml
@model ListaCompetenciaViewModel
@using System.Web

<table class="table">
   <thead>
    <tr>
      @{
        List<string> classColorsList = new List<string>{"table-primary","table-secondary","table-success","table-danger","table-warning","table-info"};
        
        foreach(var item in Model.Competencias.Zip(classColorsList,(a,b) => new {A = a, B = b}))
        {
                <th class=@item.B scope="col">@item.A.ColunaBloom</th>
        } 
      }
    </tr>
   </thead>
   <tbody>
    <tr>
      @{ 
        List<List<Competencia>> partes = new List<List<Competencia>>();
        int tamanho = 6;
        //cria partes de 6 em 6
        for (int i = 0; i < Model.Competencias.Count; i += tamanho)
        {
          partes.Add(Model.Competencias.Skip(i).Take(tamanho).ToList());
        } 
        foreach(var parte in partes)
        {
          <tr>
          @foreach(var item in parte.Zip(classColorsList,(a,b) => new {A = a, B = b}))
          {
            <td class=@item.B scope="col">@item.A.LinhaBloom</td>    
          } 
        </tr>
        }
        
      }
    </tr>
    
   </tbody>
 
</table>

<div class="text-center">  
  <h1 class="display-4">Taxonomia de Bloom</h1>
</div>

<div>
  <form method="post">
    Digite o verbo <input type="text" id="verbo" name="verbo">
    <select class="form-select" aria-label="Default select example" name="colunaBloom">
    <option selected>Selecione o verbo</option>
    @{
          HashSet<string> listaColunaBloom = new HashSet<string>();
          foreach(var item in Model.Competencias)
          {
            listaColunaBloom.Add(item.ColunaBloom);
          }
          var i=1;
          foreach(var item in listaColunaBloom)
          {
            <option value=@i>@item</option>
            i++;
          }
      }
    
    </select>

    <div>
      <button type="submit">Cadastrar</button>
    </div> 
  </form>
</div>










  

Views/Competencia/Listar.cshtml
@model ListaCompetenciaViewModel
<h1>Lista Competências</h1>
<table>
    <tr>
        <th>Id</th>
        <th>Coluna Bloom</th>
        <th>Linha Bloom</th>
    </tr>
    @{
        foreach(var item in Model.Competencias)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.ColunaBloom</td>
                <td>@item.LinhaBloom</td>
            </tr>
        } 
    }
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<h1>Bem vindo</h1>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - webappbloom</title>
    <link rel="stylesheet" href="~/wwwroot"/>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/webappbloom.styles.css" asp-append-version="true" />
    <link rel="icon" href="~/favicon.ico"/>
</head>
<body>
    <header>
         <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">webappbloom</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Competencia" asp-action="Index">Competência</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> 
                        <li>
                            <a class="nav-link text-dark" href="@Url.Action("Index", "Home")">Home </a> 
                        </li>
                        <li>
                            <a class="nav-link text-dark" href="@Url.Action("Index", "Competencia")">Competencia</a> 
                        </li>                      
                    </ul>
                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - webappbloom - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>